// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kznzybnxrgxouiycivwi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6bnp5Ym54cmd4b3VpeWNpdndpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMDkzMjUsImV4cCI6MjA2ODU4NTMyNX0.aN8Q6uvnEcKlsDFo2S8Bwohfs3UcwzTEOoNkPCvhJUU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});